### ISSUE TITLE
Relay Schalter FGS-222

### ISSUE THREAD

**Issue by madison2007** [MMore/pimatic-plugin-template#10]
hat den Relay Schalter FGS-222 schon jemand zum laufen gebracht?
oder scheitert es am plugin für pimatic?

lg Mad

**Comment by MMore** [comment]
Stehen denn im Log irgendwelche Meldungen?

**Comment by madison2007** [comment]
habe versucht das relais wie die schaltbare steckdose  
Wall Plug FGWPE-101 einzubinden.
aber das funktioniert nicht, im logfile steht das er das device nicht finden kann.
die steckdose funktioniert jedoch einwandfrei.
kann es sein das das relais in das plugin noch implementiert gehört?

**Comment by madison2007** [comment]
im log steht:  warn: no plugin found for device "fibaro_relais" of class "ZwaySwitch"
die id kann man frei vergeben, oder habe ich das falsch verstanden?

**Comment by MMore** [comment]
Hast du die Groß/Kleinschreibung evtl. nicht beachtet (bei dir "Z**w**aySwitch")? Die Class muss exakt so heißen, wie in der Hilfe angegeben. Die ID kann frei sein, ja, nur die VirtualDeviceID muss stimmen, also z.B.

```
{
  "class": "ZWaySwitch",
  "id": "fibaro_1_plug",
  "name": "Fibaro Schalter",
  "virtualDeviceId": "ZWayVDev_zway_2-0-37",
  "interval": 20
},
```

Gut möglich, dass das Gerät im ZWay anders intern dargestellt wird. Mach mal ein `curl http://<ZWAYIP>:8083/ZAutomation/api/v1/devices/<virtual device id>` und poste den Inhalt. Danke.

**Comment by madison2007** [comment]
hattest recht!
das kleine w bei ZwaySwitch war das problem!
besten dank für deine hilfe!
