### ISSUE TITLE
Authentication issues

### ISSUE THREAD

**Issue by mwittig** [MMore/pimatic-plugin-template#13]
I have some concerns about commit https://github.com/MMore/pimatic-z-way/commit/6be1c905130a3663b4b2c5be979b2acb915908c6

1) Shouldn't authentication be optional to work with older versions of the z-way?!
2) defaults for userId and password doesn't make much sense to me unless admin / "" (empty password) is a kind of factory default.

See also https://forum.pimatic.org/topic/1906/z-way-problem-with-0-9

**Comment by MMore** [comment]
Hi,

1) In my opinion it is better to force authentication for reasons of security.
2) I agree with that, but I am not sure what the factory default of z-way is currently. @thexperiments?

**Comment by mwittig** [comment]
What's the conclusion on this?

**Comment by MMore** [comment]
My first point stays the same. According 2nd: I am using pimatic with a local user and localhost. So I don't need credentials there and those config options must be optional.

**Comment by mwittig** [comment]
Thanks for the clarification. To make those config options must be optional the default values need to be replaced with `required: false`, or leave it as is if the z-way API accepts the default values.
