### ISSUE TITLE
After reboot of zway 401 errors

### ISSUE THREAD

**Issue by Wikibear** [MMore/pimatic-plugin-template#14]
Hi,

after Reboot of z-way i must restart pimatic for new authentification, too. That's a little bit boring. Why the script don't try again with 401 error to reach the server? At the moment i get a big log with 401 errors. After rebooting of pimatic the plugin should be new init and the login data will be set.

Is there another solution to fix this?

**Comment by MMore** [comment]
Hi,

sorry for the late reply. This is fixed in #17.
