### ISSUE TITLE
error after z-wave 2.2.4 update

### ISSUE THREAD

**Issue by benbeton** [MMore/pimatic-plugin-template#19]
Hi,

after updating to zwave 2.2.4 there are a lot of errors in the log:

**error updating sensor value  Cannot read property 'data' of undefined**

rolling back to 2.2.3 helps, errors gone....
if you need more information let me know. I'm running pimatic plugin v1.3.2

regards

**Comment by MMore** [comment]
Hi @benbeton,

thanks for the info. So it seemed they changed the API a little bit despite only increasing the patch level version... 

Currently I cannot update my Razberry to reproduce it. I should be able to do it within this month.

Cheers

**Comment by johnappletree** [comment]
hi @benbeton,
I updated to zwave 2.2.4 and don't have any issues.
Please check, if your specified z-wave user in the pimatic config file has access to all your rooms and sensors. In the case that no user is defined in the log file, check if the local user (in z-wave.me software) has access to them.

Best regards,

jat

**Comment by benbeton** [comment]
I'll update it again and check if there are config related things changed on my installation

**Comment by johnappletree** [comment]
@benbeton did it work?

**Comment by benbeton** [comment]
no it didn't. I updated to 2.2.4 and checked the configuration: nothing changed to the permissions. 
Even with 2.2.5 I get the error.

**Comment by Wikibear** [comment]
Go to User Managment and Edit Local User. There must be a local user. If not create one. The local user needs right to the rooms! Thats important or you get this error.

**Comment by benbeton** [comment]
just updated to 2.2.5 again, to check if the local user exits, and he exits. but the error is still there.
so I rolled back to 2.2.3.

**Comment by Wikibear** [comment]
And again it is totally recommended that the local user get access to your created rooms! If not local user is useless.

**Comment by MMore** [comment]
I updated to v2.2.5 too: no issues with pimatic-z-way.

**Comment by benbeton** [comment]
found the issue! 
Because you implemented the that **error updating sensor value Cannot read property 'data' of undefined** gives a sensor indication in the newest update, I was able to see the after 2.2.5 Update my error has come from a zway motion sensor that was changed during the 2.2.5 update. 

after I fixed that in the pimatic config, the error is gone. 
Thank you!
