### ISSUE TITLE
Zipato RFID Keypad 

### ISSUE THREAD

**Issue by DerGrafausB** [MMore/pimatic-plugin-template#20]
it is not possible to use the zway-switch with the Zipato APP.
Zipato App installed one virtual Device Switch in z-wave.me "Zipato RFID Keypad Security Mode".
I can switch it by Shellswitch, but i don't find a way to update the status.

Can you implement a device "Zipato RFID Keypad Security Mode"

My Element ID: MiniKeypadSecurityMode_11

**Comment by LeopoldKing** [comment]
Hi,

it might be easier for the developer, if you clearly explain what you want and what you did. 

Cheers

**Comment by DerGrafausB** [comment]
Hi,

in zwave,me if you want to use "Zipato RFID Keypad" you have to install a app called "Zipato RFID Keypad".

look here:

https://www.siio.de/sicherheitalarm/das-zipato-rfid-keypad-im-zway-smarthome-nutzen/

This App install in zwave.me a virtual Switch called "Zipato RFID Keypad Security Mode".

And this switch is not compatible with the zway switch in pimatic. 

You can switch it on, but then there is a bug. No State...  No switching off.

Do you need more informations?

Thank you

**Comment by LeopoldKing** [comment]
It doesn't sound like a bug or a feature request.. Are the virtual device ids identically?
Is pimatic able to access the switch in Z-Way?

**Comment by DerGrafausB** [comment]
The IDs are ok. In the Api there is the same id in the list.
ID  by copy & paste.
In Pimatic you can switch it on, the switch goes on in z-way, and then the state in pimatic is off.

If you switch it on in z-way or by device, nothing happend in pimatic.

I think you can try it, if you download the app in z-way.

**Comment by LeopoldKing** [comment]
A Z-Way switch is by default never updated in Pimatic. If you configure your device, check "interval: 0" and change it, e.g. to interval: 1, so that Pimatic is requesting an update every second.

I guess that will do the trick

**Comment by DerGrafausB** [comment]
of course i did that

**Comment by LeopoldKing** [comment]
can you send the config of your device in pimatic?

**Comment by DerGrafausB** [comment]
{
      "virtualDeviceId": "MiniKeypadSecurityMode_11",
      "interval": 1,
      "id": "keypad",
      "name": "Keypad",
      "class": "ZWaySwitch"
    }

**Comment by DerGrafausB** [comment]
I deleted the app in z-wave.me, installed it again.
Deleted the device in pimatic, restarted pimatic, added the device and now it worked.
However?!?
Nothing Changed, but it worked now.

This was not my first z-way device
