### ISSUE TITLE
error [pimatic-z-way]: error updating sensor value  Cannot read property 'data' of undefined

### ISSUE THREAD

**Issue by DerGrafausB** [MMore/pimatic-plugin-template#21]
why does it not report device ID, so I know which device makes the problem

**Comment by benbeton** [comment]
have you updated your razberry version prior 2.2.3 ? 
If yes, see this post: https://github.com/MMore/pimatic-z-way/issues/19 there is no solution right now.

**Comment by DerGrafausB** [comment]
Version z-wave.me is 2.2.5
Pimatic is up to date
I would like to see the device id in pimatic.

**Comment by benbeton** [comment]
do you get the errors described in the title in errors in the pimatic log?

**Comment by MMore** [comment]
Yeah, you are right, the sensor should report this. According code base it must be a Motion or Door/Contact sensor (see https://github.com/MMore/pimatic-z-way/blob/master/z-way.coffee#L272 and https://github.com/MMore/pimatic-z-way/blob/master/z-way.coffee#L376).
Will be changed within the next release.

**Comment by Wikibear** [comment]
error [pimatic-z-way]: error updating sensor value for power Cannot read property 'data' of undefined

Get the same error. I have add new devices yesterday and both devices doesn't work. My other old device work without error. That's confusing me.

**Comment by rbr101** [comment]
Hi, i just installed z-wave.me added the license and i get the same error in pimatic when i try to add the z-way devices: 

updating sensor value failed with Cannot read property 'data' of undefined

**Comment by benbeton** [comment]
which z-wave raspberry version do you use?

**Comment by rbr101** [comment]
I'm using the z-wave.me uzb dongle (https://www.z-wave.me/index.php?id=28), if i look @info -> Firmware version it says: Firmware version	v2.3.0. I ins

talled it as per instructions on http://razberry.z-wave.me/index.php?id=24

The devices in z-wave.me application are recognised and working fine.

**Comment by Wikibear** [comment]
Its recommend that a local user is created with required access via lan and - that is most important - that this user have access to your devices eg rooms!

https://i.imgur.com/QsvYZS0.png

**Comment by rbr101** [comment]
Thanks, i deleted the existing local user and created a new one. Now it works fine.
Somehow the local user did not have privs to access the devices.
