### ISSUE TITLE
Implement z-wave thermostat device

### ISSUE THREAD

**Issue by Clark2309** [MMore/pimatic-plugin-template#4]
The command classes are
Basic, ThermostatSetPoint, ClimateControlSchedule, ManufacturerSpecific, Protection, Battery, Clock, Wakeup, Version, MultiCmd,

I will try to get familiar with the code and implement this. If someone else ist faster, I can give more information about the device

**Comment by benbeton** [comment]
thats great! I changed my thermostats to the new ones and they work great! 
Is there a plan to add "boost" to the thermostat? 

Boost should set the temp to 28, thats the max of Danfoss thermostats

thank you for the basic implementation!

**Comment by MMore** [comment]
I wanted to test it a little bit in my local environment at first. Then I might implement more features.

For instance I have issues with my Danfoss thermostats that sometimes not correctly processes setpoint change requests. So I change the setpoint to 18 degree. I see this change in pimatic & Z-Way, but after some minutes it resets back to the previous setpoint. But that's not a pimatic but more a z-way issue... I am investigating...
