### ISSUE TITLE
adding Luminescence Sensor (Fibaro Eye)

### ISSUE THREAD

**Issue by benbeton** [MMore/pimatic-plugin-template#6]
Hi,

my Fibaro Eye is working great (motion and temp. Sensor) 

Would it be possible to add the Luminescence Sensor? 

regards

**Comment by benbeton** [comment]
done: http://forum.pimatic.org/topic/1139/more-z-wave-devices/8

```
{
  "class": "ZWayTemperatureSensor",
  "id": "fibaro_lum_sensor",
  "name": "{name}",
  "virtualDeviceId": "{your ZWayVDev_zway_ID}"
}
```

**Comment by MMore** [comment]
I just added a new dedicated sensor for Luminiscence.
